version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    branches:
      only: develop
    steps:
      - checkout

      - restore_cache:
          key: cache

      - save_cache:
          paths:
            - ~/.stack
          key: cache

      - run: stack setup
      - run: stack build
      - run: ./publish.sh
