version: 2
jobs:
  build:
    docker:
      - image: haskell
    branches:
      only: develop
    steps:
      - checkout

      - restore_cache:
          key: cache

      - save_cache:
          paths:
            - ~/.stack
          key: cache

      - run: stack install
      - run: stack exec blog build 